### ISSUE TITLE
Linux Install Issue

### ISSUE THREAD

**Issue by darth-cheney** [LivelyKernel/lively.installer#10]
When following the README instructions for installation on Xubuntu, I'm getting a ton of the following errors (small sample below) during the babel install portion:
  
```
[flatn] downloading babel-core@^6.21.0 - https://registry.npmjs.org/babel-core/-/babel-core-6.26.0.tgz
(node:11843) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: EXDEV: cross-device link not permitted, rename '/tmp/package_install_tmp/babel-core/README.md' -> '/home/ecgade/projects/lively.next/lively.next-node_modules/babel-core/6.26.0/README.md'
(node:11843) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:11843) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: EXDEV: cross-device link not permitted, rename '/tmp/package_install_tmp/babel-core/index.js' -> '/home/ecgade/projects/lively.next/lively.next-node_modules/babel-core/6.26.0/index.js'
(node:11843) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: EXDEV: cross-device link not permitted, rename '/tmp/package_install_tmp/babel-core/package-lock.json' -> '/home/ecgade/projects/lively.next/lively.next-node_modules/babel-core/6.26.0/package-lock.json'
(node:11843) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 4): Error: EXDEV: cross-device link not permitted, rename '/tmp/package_install_tmp/babel-core/package.json' -> '/home/ecgade/projects/lively.next/lively.next-node_modules/babel-core/6.26.0/package.json'
(node:11843) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 5): Error: EXDEV: cross-device link not permitted, rename '/tmp/package_install_tmp/babel-core/register.js' -> '/home/ecgade/projects/lively.next/lively.next-node_modules/babel-core/6.26.0/register.js'
```
  
And so on, ultimately failing with:
```
Download of babel-core@^6.21.0 failed: TypeError: Cannot read property 'writeLvInfo' of null
    at packageDownload (file:///home/ecgade/projects/lively.next/flatn/flatn-cjs.js:1049:17)
    at <anonymous>
Error occurred during installation: TypeError: Cannot read property 'writeLvInfo' of null
    at packageDownload (file:///home/ecgade/projects/lively.next/flatn/flatn-cjs.js:1049:17)
    at <anonymous>
```
  
I have no idea why `EXDEV` is the error here; I do not have multiple mount points on this machine

**Comment by rksm** [comment]
This is an unforeseen interaction between [flatn](https://github.com/rksm/flatn/blob/master/download.js#L48) which we use to install packages so that all Lively and nodejs packages are only in one file system location but still locatable by nodejs and lively.installer which in addition [links](https://github.com/LivelyKernel/lively.installer/blob/master/package.js#L132) packages.  The latter is not really necessary anymore, it was before we had flatn.  I'll make a test and see if we can remove that.

Thanks for reporting!

**Comment by rksm** [comment]
OK, should be fixed now.
