### ISSUE TITLE
lively.next install failed on Debian/GNU Linux NodeJS 9.3.0

### ISSUE THREAD

**Issue by mdittmer** [LivelyKernel/lively.installer#11]
I ran:

```bash
mkdir lively.next
cd lively.next
curl -o- https://raw.githubusercontent.com/LivelyKernel/lively.installer/master/web-install.sh | bash 2>&1 | tee web-install.log
```

Here's the last bit of `web-install.log`:

```
make: Leaving directory '/home/user/src/lively.next/lively.next-node_modules/leveldown/1.5.0/build'
[flatn] leveldown build done
build lively.modules and its dependencies
build mocha-es6 and its dependencies
build lively-system-interface and its dependencies
build lively.installer and its dependencies
build flatn and its dependencies
build lively.serializer2 and its dependencies
build lively.graphics and its dependencies
build lively.keyboard and its dependencies
build lively.morphic and its dependencies
build lively.mirror and its dependencies
build lively.sync and its dependencies
build lively.notifications and its dependencies
build lively.changesets and its dependencies
build lively.shell and its dependencies
build lively.server and its dependencies
build lively.2lively and its dependencies
build lively.user and its dependencies
build lively.git and its dependencies
build lively.traits and its dependencies
build lively.halos and its dependencies
build lively.components and its dependencies
build lively.ide and its dependencies
build lively.headless and its dependencies
[flatn] puppeteer build starting

Chromium downloaded to /home/user/src/lively.next/lively.next-node_modules/puppeteer/0.12.0/.local-chromium/linux-508693
[flatn] puppeteer build done
build lively.freezer and its dependencies
compiling flatn

Error: Command failed: npm run build
/home/user/src/lively.next/lively.lang/index.js:1
(function (exports, require, module, __filename, __dirname) { import * as string from "./string.js";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/src/lively.next/flatn/tools/build-cjs.js:3:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flatn@1.3.3 build: `node tools/build-cjs.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flatn@1.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-07-17T15_27_31_522Z-debug.log

> flatn@1.3.3 build /home/user/src/lively.next/flatn
> node tools/build-cjs.js


/home/user/src/lively.next/lively.lang/index.js:1
(function (exports, require, module, __filename, __dirname) { import * as string from "./string.js";
                                                              ^^^^^^

SyntaxError: Unexpected token import
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:152:10)
    at Module._compile (module.js:624:28)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
    at Module.require (module.js:604:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/user/src/lively.next/flatn/tools/build-cjs.js:3:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! flatn@1.3.3 build: `node tools/build-cjs.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the flatn@1.3.3 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-07-17T15_27_31_522Z-debug.log

=> synchronizing with object database from lively-next.org...
Error occurred during installation: (SystemJS) ENOENT: no such file or directory, open '/home/user/src/lively.next/lively.storage/dist/pouchdb-adapter-mem.js'
	Error: ENOENT: no such file or directory, open '/home/user/src/lively.next/lively.storage/dist/pouchdb-adapter-mem.js'
	Error loading /home/user/src/lively.next/lively.storage/dist/pouchdb-adapter-mem.js as "pouchdb-adapter-mem" from /home/user/src/lively.next/lively.storage/database.js
```

**Comment by rksm** [comment]
@merryman did something change in flatn?

**Comment by merryman** [comment]
It is not an issue with flatn but with the way we currently build the static versions of the lively packages. If the install script is run once more again, it will work every time from then on. I will push a fix once I find the time.

EDIT: Problem is now fixed. It was due to some packages (such as lively.lang) not specifying all the dev dependencies they actually require. Due to the centralised dependency folder of flatn, this only causes problems on the initial build. We should probably include a warning in flatn that comes up when it detects that a dependency can be resolved yet has not been specified by the dependency graph of the package itself.

**Comment by mdittmer** [comment]
Thanks for the follow up! I'll run it a second time and see whether that
works.

**Comment by rksm** [comment]
@merryman Thank you!!
