### ISSUE TITLE
Unable to open a world using a fresh install on OSX

### ISSUE THREAD

**Issue by andyburnett** [LivelyKernel/lively.installer#12]
Node 8.11.4
OSX 10.13.6

Install using the curl command on this repo.
Everything installs without errors.
index.html loads, but clicking on any of the existing worlds results in:

(SystemJS) Cannot read http://localhost:9011/kld-intersections: Not Found 404
	Error: Cannot read http://localhost:9011/kld-intersections: Not Found 404
	    at WebDAVResource_read_ (http://localhost:9011/lively.resources/src/http-resource.js:525:23)
	Error loading http://localhost:9011/kld-intersections as "kld-intersections" from http://localhost:9011/lively.components/widgets.js

**Comment by merryman** [comment]
This is some missing dependency updates I to the components package. I will soon push a fix for this.

**Comment by andyburnett** [comment]
@merryman Great, I am looking forward to playing with the system.

**Comment by andyburnett** [comment]
I just ran update.sh - because I saw that you had closed #11 and wondered if this would solve my problem. I now get a new error message.

installing dependencies of lively.morphic
TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at npmSearchForVersions (file:///Users/andy/Documents/Projects/lively.next/flatn/flatn-cjs.js:61:57)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[flatn] retrying download of kld-intersections@4.1
TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at npmSearchForVersions (file:///Users/andy/Documents/Projects/lively.next/flatn/flatn-cjs.js:61:57)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[flatn] retrying download of kld-intersections@4.1
TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at npmSearchForVersions (file:///Users/andy/Documents/Projects/lively.next/flatn/flatn-cjs.js:61:57)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[flatn] retrying download of kld-intersections@4.1
TypeError: Cannot destructure property `name` of 'undefined' or 'null'.
    at npmSearchForVersions (file:///Users/andy/Documents/Projects/lively.next/flatn/flatn-cjs.js:61:57)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Download of kld-intersections@4.1 failed: Error: Cannot find npm package for kld-intersections@4.1
    at npmSearchForVersions (file:///Users/andy/Documents/Projects/lively.next/flatn/flatn-cjs.js:65:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
Error occurred during installation: Error: Cannot find npm package for kld-intersections@4.1
    at npmSearchForVersions (file:///Users/andy/Documents/Projects/lively.next/flatn/flatn-cjs.js:65:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by andyburnett** [comment]
@merryman I have just tried doing a new install with the curl script, and I seem to get an identical error.

**Comment by merryman** [comment]
Hey, no #11 was a different issue, but please run update.sh again now. I pushed a fix for the problematic version.

**Comment by andyburnett** [comment]
Great, that fixed it.
