### ISSUE TITLE
lively.installer crashes on OSX with Node v.6.3.11 (LTS)

### ISSUE THREAD

**Issue by mroeder** [LivelyKernel/lively.installer#7]
I was unable to install lively.next using the instructions given within the README:
```
$ curl -o- https://raw.githubusercontent.com/LivelyKernel/lively.installer/master/web-install.sh | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2205  100  2205    0     0  16020      0 --:--:-- --:--:-- --:--:-- 16094
=> Downloading lively.installer from git to 'lively.next/lively.installer'
=> Cloning into 'lively.next/lively.installer'...
remote: Counting objects: 526, done.
remote: Total 526 (delta 0), reused 0 (delta 0), pack-reused 526
Receiving objects: 100% (526/526), 970.70 KiB | 0 bytes/s, done.
Resolving deltas: 100% (325/325), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
* master
=> Downloading flatn from git to 'lively.next/flatn'
=> Cloning into 'lively.next/flatn'...
remote: Counting objects: 530, done.
remote: Total 530 (delta 0), reused 0 (delta 0), pack-reused 530
Receiving objects: 100% (530/530), 910.65 KiB | 0 bytes/s, done.
Resolving deltas: 100% (337/337), done.
Already on 'master'
Your branch is up-to-date with 'origin/master'.
* master
=> lively.installer sucessfully downloaded & intialized
[lively.modules] Could not find path to systemjs-plugin-babel but babel! Will fallback but there might be features in lively.modules that won't work!
Installing lively.system packages into lively.next
Error in prepareCodeForCustomCompile of file:///~/lively.next/lively.installer/index.js TypeError: Object.getOwnPropertyDescriptors is not a function
    at Object.dissoc (lively.next/lively.installer/deps/lively.modules.js:3735:28)
    at Object.stringify (lively.next/lively.installer/deps/lively.modules.js:21827:22)
    at Object.evalCodeTransform (lively.next/lively.installer/deps/lively.modules.js:27336:27)
    at prepareCodeForCustomCompile (lively.next/lively.installer/deps/lively.modules.js:73989:46)
    at SystemJSLoader._callee11$ (lively.next/lively.installer/deps/lively.modules.js:73195:39)
    at tryCatch (lively.next/lively.installer/deps/lively.modules.js:63:40)
    at GeneratorFunctionPrototype.invoke [as _invoke] (lively.next/lively.installer/deps/lively.modules.js:331:22)
    at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (lively.next/lively.installer/deps/lively.modules.js:96:21)
    at step (lively.next/lively.installer/deps/lively.modules.js:72856:30)
    at lively.next/lively.installer/deps/lively.modules.js:72867:13
Error!Error: (SystemJS) [BABEL] lively.next/lively.installer/index.js: Using removed Babel 5 option: base.modules - Use the corresponding module transform plugin in the `plugins` option. Check out http://babeljs.io/docs/plugins/#modules
	ReferenceError: [BABEL] lively.next/lively.installer/index.js: Using removed Babel 5 option: base.modules - Use the corresponding module transform plugin in the `plugins` option. Check out http://babeljs.io/docs/plugins/#modules
	    at e.error (lively.next/lively.installer/deps/babel.min.js:5:7623)
	    at e.mergeOptions (lively.next/lively.installer/deps/babel.min.js:2:10515)
	    at e.init (lively.next/lively.installer/deps/babel.min.js:2:13142)
	    at n.initOptions (lively.next/lively.installer/deps/babel.min.js:2:22551)
	    at new n (lively.next/lively.installer/deps/babel.min.js:2:21555)
	    at e.transform (lively.next/lively.installer/deps/babel.min.js:14:18609)
	    at Object.s [as transform] (lively.next/lively.installer/deps/babel.min.js:1:1380)
	Error loading lively.next/lively.installer/index.js
```
(exact path removed from this log and replaced by `lively.next` or `~/lively.next`

**Comment by mroeder** [comment]
Works fine with Node v.8.5.0 however (most recent).

**Comment by rksm** [comment]
Thank you for testing!  I think at this point we just go with the flow and refuse to install on something < node 7 (1c50391).  I hope this will be enough to avoid confusion.
